/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ml_dmlc_mxnet_LibInfo */

#ifndef _Included_ml_dmlc_mxnet_LibInfo
#define _Included_ml_dmlc_mxnet_LibInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ml_dmlc_mxnet_LibInfo_mxGetLastError
  (JNIEnv *, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayCreateNone
 * Signature: (Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayCreateNone
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayCreate
 * Signature: ([IIIIILml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayCreate
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayGetShape
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;Lscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayGetShape
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayWaitAll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayWaitAll
  (JNIEnv *, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayWaitToRead
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayWaitToRead
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxListFunctions
 * Signature: (Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxListFunctions
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxFuncDescribe
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;Lml/dmlc/mxnet/Base/RefInt;Lml/dmlc/mxnet/Base/RefInt;Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxFuncDescribe
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxFuncGetInfo
 * Signature: (JLml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefInt;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxFuncGetInfo
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxFuncInvoke
 * Signature: (J[J[F[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxFuncInvoke
  (JNIEnv *, jobject, jlong, jlongArray, jfloatArray, jlongArray);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArraySyncCopyToCPU
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArraySyncCopyToCPU
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArraySlice
 * Signature: (JIILml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArraySlice
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArraySyncCopyFromCPU
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArraySyncCopyFromCPU
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayLoad
 * Signature: (Ljava/lang/String;Lml/dmlc/mxnet/Base/RefInt;Lscala/collection/mutable/ArrayBuffer;Lml/dmlc/mxnet/Base/RefInt;Lscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayLoad
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArraySave
 * Signature: (Ljava/lang/String;[J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArraySave
  (JNIEnv *, jobject, jstring, jlongArray, jobjectArray);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxNDArrayGetContext
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayGetContext
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreCreate
 * Signature: (Ljava/lang/String;Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreCreate
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreInit
 * Signature: (JI[I[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreInit
  (JNIEnv *, jobject, jlong, jint, jintArray, jlongArray);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStorePush
 * Signature: (JI[I[JI)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStorePush
  (JNIEnv *, jobject, jlong, jint, jintArray, jlongArray, jint);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStorePull
 * Signature: (JI[I[JI)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStorePull
  (JNIEnv *, jobject, jlong, jint, jintArray, jlongArray, jint);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreSetUpdater
 * Signature: (JLml/dmlc/mxnet/MXKVStoreUpdater;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreSetUpdater
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreIsWorkerNode
 * Signature: (Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreIsWorkerNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreGetType
 * Signature: (JLml/dmlc/mxnet/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreGetType
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreSendCommmandToServers
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreSendCommmandToServers
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreBarrier
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreBarrier
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreGetGroupSize
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreGetGroupSize
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxKVStoreGetRank
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxKVStoreGetRank
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxListDataIters
 * Signature: (Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxListDataIters
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterCreateIter
 * Signature: (J[Ljava/lang/String;[Ljava/lang/String;Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterCreateIter
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterGetIterInfo
 * Signature: (JLml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefString;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterGetIterInfo
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterBeforeFirst
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterBeforeFirst
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterNext
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterNext
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterGetLabel
 * Signature: (JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterGetLabel
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterGetData
 * Signature: (JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterGetData
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterGetIndex
 * Signature: (JLscala/collection/mutable/ListBuffer;Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterGetIndex
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxDataIterGetPadNum
 * Signature: (JLml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxDataIterGetPadNum
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorOutputs
 * Signature: (JLscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorOutputs
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorForward
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorForward
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorBackward
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorBackward
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorPrint
 * Signature: (JLml/dmlc/mxnet/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorPrint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorSetMonitorCallback
 * Signature: (JLml/dmlc/mxnet/MXMonitorCallback;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorSetMonitorCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolListAtomicSymbolCreators
 * Signature: (Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolListAtomicSymbolCreators
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolGetAtomicSymbolInfo
 * Signature: (JLml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefInt;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lml/dmlc/mxnet/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolGetAtomicSymbolInfo
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolCreateAtomicSymbol
 * Signature: (J[Ljava/lang/String;[Ljava/lang/String;Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolCreateAtomicSymbol
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolSetAttr
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolSetAttr
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolCompose
 * Signature: (JLjava/lang/String;[Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolCompose
  (JNIEnv *, jobject, jlong, jstring, jobjectArray, jlongArray);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolCreateVariable
 * Signature: (Ljava/lang/String;Lml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolCreateVariable
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolGetAttr
 * Signature: (JLjava/lang/String;Lml/dmlc/mxnet/Base/RefString;Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolGetAttr
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolListArguments
 * Signature: (JLscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolListArguments
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolCopy
 * Signature: (JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolCopy
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolListAuxiliaryStates
 * Signature: (JLscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolListAuxiliaryStates
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolListOutputs
 * Signature: (JLscala/collection/mutable/ArrayBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolListOutputs
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolCreateGroup
 * Signature: ([JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolCreateGroup
  (JNIEnv *, jobject, jlongArray, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolPrint
 * Signature: (JLml/dmlc/mxnet/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolPrint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolGetInternals
 * Signature: (JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolGetInternals
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolInferType
 * Signature: (J[Ljava/lang/String;[ILscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolInferType
  (JNIEnv *, jobject, jlong, jobjectArray, jintArray, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolInferShape
 * Signature: (JI[Ljava/lang/String;[I[ILscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lml/dmlc/mxnet/Base/RefInt;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolInferShape
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jintArray, jintArray, jobject, jobject, jobject, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolGetOutput
 * Signature: (JILml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolGetOutput
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxSymbolSaveToJSON
 * Signature: (JLml/dmlc/mxnet/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxSymbolSaveToJSON
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxExecutorBindX
 * Signature: (JIII[Ljava/lang/String;[I[II[J[J[I[JLml/dmlc/mxnet/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxExecutorBindX
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobjectArray, jintArray, jintArray, jint, jlongArray, jlongArray, jintArray, jlongArray, jobject);

/*
 * Class:     ml_dmlc_mxnet_LibInfo
 * Method:    mxRandomSeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxRandomSeed
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
